# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Josh Kelly
email: josh.kelly27@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Independent web dev and 3DS homebrew developer. Good with HTML5, PHP7 and JavaScript.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thejsa.github.io" # the base hostname & protocol for your site
twitter_username: kgbsquirrel
github_username:  thejsa

# Build settings
markdown: kramdown
